import xml.etree.ElementTree as ET
from xml.dom import minidom
import networkx as nx
import matplotlib.pyplot as plt

def generate_orthoxml(species_data, groups, output_file="output/orthologs.xml"):
    """
    Generate an OrthoXML file representing orthologous relationships among species.

    Parameters:
    - species_data: DataFrame with at least 'species_id' and 'species_name'.
    - groups: A dictionary where each key is a group ID and the value is a list of species_ids in that group.
    - output_file: Output filename for the OrthoXML file.
    """
    # Create the root element
    print('Performing OrthoXML Generation..')
    root = ET.Element("orthoXML", attrib={"version": "0.3", "origin": "Generated by Python"})

    # Create species elements
    for _, row in species_data.iterrows():
        species = ET.SubElement(root, "species", attrib={"id": str(row["species_id"]), "name": row["species_name"]})
        database = ET.SubElement(species, "database", attrib={"name": "SampleDB", "version": "1.0"})
        genes_element = ET.SubElement(database, "genes")
        # Assume each species has a gene with the same ID as the species for simplicity
        gene = ET.SubElement(genes_element, "gene", attrib={"id": str(row["species_id"]), "geneId": f"gene_{row['species_id']}"})

    # Create groups (orthologous groups)
    for group_id, members in groups.items():
        group_element = ET.SubElement(root, "groups")
        ortholog_group = ET.SubElement(group_element, "orthologGroup", attrib={"id": str(group_id)})
        for member_id in members:
            ET.SubElement(ortholog_group, "geneRef", attrib={"id": str(member_id)})

    # Generate and save the XML
    xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    with open(output_file, "w") as f:
        f.write(xml_str)

    print(f"OrthoXML file generated: {output_file}")


def parse_orthoxml(file_path):
    """
    Parse the OrthoXML file to extract species and orthologous groups.

    Parameters:
    - file_path: Path to the OrthoXML file.

    Returns:
    - species_dict: Dictionary of species with species_id as keys and species_name as values.
    - groups: List of groups, where each group is a list of gene IDs (species IDs).
    """
    tree = ET.parse(file_path)
    root = tree.getroot()

    # Extract species information
    species_dict = {}
    for species in root.findall("species"):
        species_id = species.get("id")
        species_name = species.get("name")
        species_dict[species_id] = species_name

    # Extract orthologous groups
    groups = []
    for group in root.findall(".//orthologGroup"):
        group_ids = [gene.get("id") for gene in group.findall("geneRef")]
        groups.append(group_ids)

    return species_dict, groups

def visualize_orthologs_multiple_layouts(file_path):
    """
    Visualize the orthologous groups using four different layouts for comparison.

    Parameters:
    - file_path: Path to the OrthoXML file.
    """
    # Parse OrthoXML to get species and groups
    species_dict, groups = parse_orthoxml(file_path)

    # Create a graph to represent orthologous groups
    G = nx.Graph()

    # Add nodes for each species
    for species_id, species_name in species_dict.items():
        G.add_node(species_id, label=species_name)

    # Add edges for each orthologous group
    for group_id, group in enumerate(groups):
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                G.add_edge(group[i], group[j], group_id=group_id)

    # Define the layouts to test
    layouts = {
        "Spring Layout": nx.spring_layout(G, seed=42),
        "Circular Layout": nx.circular_layout(G),
        "Kamada-Kawai Layout": nx.kamada_kawai_layout(G),
        "Spectral Layout": nx.spectral_layout(G)
    }

    # Create subplots for each layout
    fig, axes = plt.subplots(2, 2, figsize=(16, 16))
    fig.suptitle("Orthologous Groups Visualization with Different Layouts", fontsize=16)

    # Plot each layout
    for ax, (layout_name, pos) in zip(axes.flatten(), layouts.items()):
        # Draw nodes with reduced size and edgecolors
        nx.draw_networkx_nodes(G, pos, ax=ax, node_color="skyblue", node_size=100, edgecolors="black")

        # Draw edges with different colors based on group_id for visual differentiation
        for group_id, color in enumerate(plt.cm.tab20.colors):
            group_edges = [(u, v) for u, v, d in G.edges(data=True) if d["group_id"] == group_id]
            nx.draw_networkx_edges(G, pos, edgelist=group_edges, ax=ax, alpha=0.6, edge_color=[color])

        # Draw labels with a default for missing nodes
        labels = {node: species_dict.get(node, "Unknown") for node in G.nodes}
        nx.draw_networkx_labels(G, pos, labels, font_size=6, font_color="black", ax=ax)

        ax.set_title(layout_name)
        ax.axis("off")

    plt.tight_layout()
    plt.subplots_adjust(top=0.93)  # Adjust for the main title
    plt.show()
    
def visualize_orthologs(file_path):
    """
    Visualize the orthologous groups in the OrthoXML file as a network graph.

    Parameters:
    - file_path: Path to the OrthoXML file.
    """
    # Parse OrthoXML to get species and groups
    species_dict, groups = parse_orthoxml(file_path)

    # Create a graph to represent orthologous groups
    G = nx.Graph()

    # Add nodes for each species
    for species_id, species_name in species_dict.items():
        G.add_node(species_id, label=species_name)

    # Add edges for each orthologous group, skipping missing species
    for group in groups:
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                if group[i] in species_dict and group[j] in species_dict:
                    G.add_edge(group[i], group[j])

    # Draw the graph
    plt.figure(figsize=(12, 8))
    pos = nx.spring_layout(G, seed=42)  # Use spring layout for a better visual spread
    
    # Handle labels by using species_dict with a default for missing nodes
    labels = {node: species_dict.get(node, "Unknown") for node in G.nodes}

    # Draw nodes, edges, and labels
    nx.draw_networkx_nodes(G, pos, node_color="skyblue", node_size=500, edgecolors="black")
    nx.draw_networkx_edges(G, pos, width=1.5, alpha=0.6)
    nx.draw_networkx_labels(G, pos, labels, font_size=8, font_color="black")

    plt.title("Orthologous Groups Visualization")
    plt.axis("off")
    plt.show()

    """
    Visualize the orthologous groups in the OrthoXML file as a network graph.

    Parameters:
    - file_path: Path to the OrthoXML file.
    """
    # Parse OrthoXML to get species and groups
    species_dict, groups = parse_orthoxml(file_path)

    # Create a graph to represent orthologous groups
    G = nx.Graph()

    # Add nodes for each species
    for species_id, species_name in species_dict.items():
        G.add_node(species_id, label=species_name)

    # Add edges for each orthologous group
    for group in groups:
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                G.add_edge(group[i], group[j])

    # Draw the graph
    plt.figure(figsize=(12, 8))
    pos = nx.spring_layout(G, seed=42)  # Use spring layout for a better visual spread
    labels = {node: species_dict[node] for node in G.nodes}

    # Draw nodes, edges, and labels
    nx.draw_networkx_nodes(G, pos, node_color="skyblue", node_size=500, edgecolors="black")
    nx.draw_networkx_edges(G, pos, width=1.5, alpha=0.6)
    nx.draw_networkx_labels(G, pos, labels, font_size=8, font_color="black")

    plt.title("Orthologous Groups Visualization")
    plt.axis("off")
    plt.show()